services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KEYBOARD=${KEYBOARD}
        - KEYMAP=${KEYMAP}
    volumes:
      - ../:/home/user/app
      - ../keyboards:/home/user/qmk_firmware/keyboards
      - ../dist:/home/user/qmk_userspace
    tty: true
